"""create mastery and learning path tables

Revision ID: f921858f7083
Revises: 9dcf18c8e714
Create Date: 2026-09-22 08:59:49.655171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f921858f7083'
down_revision: Union[str, Sequence[str], None] = '9dcf18c8e714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_skill_id', sa.String(length=36), nullable=True),
    sa.Column('recommended_difficulty', sa.String(length=20), nullable=False),
    sa.Column('reason_for_change', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_status'), 'learning_paths', ['status'], unique=False)
    op.create_index(op.f('ix_learning_paths_student_id'), 'learning_paths', ['student_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_target_skill_id'), 'learning_paths', ['target_skill_id'], unique=False)
    op.create_table('skill_mastery',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'skill_id', name='uq_student_skill_mastery')
    )
    op.create_index(op.f('ix_skill_mastery_skill_id'), 'skill_mastery', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_mastery_student_id'), 'skill_mastery', ['student_id'], unique=False)
    op.create_table('learning_path_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_items_item_id'), 'learning_path_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_learning_path_items_path_id'), 'learning_path_items', ['path_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_path_items_path_id'), table_name='learning_path_items')
    op.drop_index(op.f('ix_learning_path_items_item_id'), table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_index(op.f('ix_skill_mastery_student_id'), table_name='skill_mastery')
    op.drop_index(op.f('ix_skill_mastery_skill_id'), table_name='skill_mastery')
    op.drop_table('skill_mastery')
    op.drop_index(op.f('ix_learning_paths_target_skill_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_student_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_status'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
